#+title: Pacdiff.el
#+author: Fabian Brosda
#+date: 2022:12:22

[[https://melpa.org/#/pacdiff][file:https://melpa.org/packages/pacdiff-badge.svg]]

* About
This package provides a small wrapper around the pacdiff utility used
on Arch Linux systems to update configuration files after package
updates.

The package provides a buffer with an overview, with all files, which
need maintenance.  You can then view the original configuration and
the pacnew/pacsave version via ediff to merge the changes.
Furthermore the buffer offers shortcuts to remove or overwrite with
the pacnew/pacsave file.

* Get Started
- Install the package
- When loaded call the function ~pacdiff~, this will create a buffer,
  which shows all pacnew/pacsave files, which needs merging.  See the
  mode description for available key bindings.


* Status
Main functionality (edit, remove, overwrite) is available.
Visualization of which changes have been made to a file could be
improved.  The package messes with system configurations and needs
root permissions to do so -> Take extra care when using it.

* License
BSD 3-Clause License, s.a. [[file:LICENSE]]
